"""empty message

Revision ID: 0daa0acd5042
Revises: 70e970adcb0f
Create Date: 2019-04-25 21:25:28.759000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0daa0acd5042'
down_revision = '70e970adcb0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'users_perm_key', 'users', type_='unique')
    op.drop_column('users', 'perm')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('perm', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.create_unique_constraint(u'users_perm_key', 'users', ['perm'])
    # ### end Alembic commands ###
